version: "3.9"
services:
  app:
    build:
      context: .
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    image: ipinfo-dev:alpine
    container_name: ipinfo-dev
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
      - /home/dev/.gitconfig:/home/dev/.gitconfig:ro
      - /home/dev/.ssh:/home/dev/.ssh:ro
    environment:
      - GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=yes
    tty: true
